name: Update Stars

on:
  schedule:
    - cron: '0 3 * * 0'  # 每周日午夜运行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
      
      - name: Clone classifier repository
        run: |
          git clone https://github.com/b1ank1108/LLM-Star-Classifier.git
          
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        working-directory: ./LLM-Star-Classifier
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create config file
        working-directory: ./LLM-Star-Classifier
        run: |
          cp config.yaml.example config.yaml
          sed -i "s|\${TOKEN}|${{ secrets.TOKEN }}|g" config.yaml
          sed -i "s|\${USERNAME}|${{ secrets.USERNAME }}|g" config.yaml
          sed -i "s|\${OPENAI_API_BASE}|${{ secrets.OPENAI_API_BASE }}|g" config.yaml
          sed -i "s|\${OPENAI_MODEL}|${{ secrets.OPENAI_MODEL }}|g" config.yaml
          sed -i "s|\${OPENAI_API_KEY}|${{ secrets.OPENAI_API_KEY }}|g" config.yaml
          
      - name: Fetch and classify stars
        working-directory: ./LLM-Star-Classifier
        run: |
          cp -r ../data ./
          python main.py fetch
          python main.py classify -u
          python main.py gen-readme
          
      - name: Copy generated files
        run: |
          cp ./LLM-Star-Classifier/STAR.md ./README.md
          cp -r ./LLM-Star-Classifier/data ./
          rm -rf ./LLM-Star-Classifier
          
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update stars - $(date '+%Y-%m-%d %H:%M:%S')" && git push)